version: '3.9'

networks:
  checdoc-networks:
    name: checdoc-networks

volumes:
  checdoc-data:
    name: checdoc-data

services:
  # db:
  #   image: postgres
  #   container_name: postgres
  #   restart: always
  #   volumes:
  #     - checdoc-data:/data/db:/var/lib/postgresql/data
  #   env_file:
  #     - ./backend/.env
  #   ports:
  #     - "5432:5432"
  #   networks:
  #     - checdoc-networks

  backend:
    image: checdoc-backend
    container_name: checdoc-backend
    build: ./backend
    restart: always
    env_file:
      - ./backend/.env
    # command: python -m gunicorn checdoc.wsgi:application --reload --workers 4
    command: python manage.py runserver 0.0.0.0:8001
    volumes:
      - ./backend:/backend
    working_dir: /backend
    ports:
      - "8001"
    networks:
      - checdoc-networks

  server:
    image: nginx
    restart: always
    container_name: checdoc-server
    volumes:
      - ./backend/media:/media
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 8000:80
    networks:
    - checdoc-networks
    depends_on:
      - backend


    