# Generated by Django 4.2.1 on 2023-05-27 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VideoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('programType', models.CharField(choices=[('serie', 'Serie'), ('movie', 'Movie')], max_length=100)),
                ('releaseYear', models.IntegerField()),
                ('image_url', models.ImageField(height_field='image_height', upload_to='', width_field='image_width')),
                ('image_width', models.IntegerField(blank=True, null=True)),
                ('image_height', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
